# Generated by Django 3.1.4 on 2020-12-20 13:56

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(help_text='Enter authors name and surname')),
                ('title', models.TextField(help_text='Enter title')),
                ('pub_date', models.DateField()),
                ('ISBN', models.IntegerField()),
                ('no_pages', models.IntegerField()),
                ('cover', models.URLField()),
                ('language', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
