# Generated by Django 3.1.4 on 2020-12-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='ISBN',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='no_pages',
            field=models.TextField(),
        ),
    ]
